import clsxm from "components/lib/clsxm";
import type { Metadata } from "next";
import { Inter, Michroma, Poppins } from "next/font/google";
// import "./globals.css";

const inter = Inter({ 
  subsets: ["latin"] ,
  display: 'swap',
});
const poppins = Poppins({
  weight: ["400", "500", "700"],
  subsets: ['latin'],
  display: 'block',
  variable: '--font-poppins',
})
const michroma = Michroma({
  weight: "400",
  subsets: ['latin'],
  display: 'swap',
  fallback: ['poppins'],
  variable: '--font-michroma'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // console.log(poppins.variable, michroma.variable, inter.variable)

  return (
    <html lang="en">
      <body className={`${poppins.variable} ${michroma.variable}`}>{children}</body>
    </html>
  );
}
